# devmode environment configuration for Herd
#

devmode_status() {
    local status=0
    devmode::docker_desktop_status || status=1
    devmode::compose_status "${HOME}/Containers/forgejo" || status=1
    devmode::compose_status "${HOME}/Containers/mailpit" || status=1
    devmode::app_status "Herd" || status=1
    return "$status"
}

devmode_up() {
    local status=0
    devmode::docker_desktop_launch || status=1
    devmode::compose_up "${HOME}/Containers/forgejo" || status=1
    devmode::compose_up "${HOME}/Containers/mailpit" || status=1
    devmode::app_launch "Herd" || status=1
    return "$status"
}

devmode_down() {
    local status=0
    devmode::app_quit "Herd" || status=1
    devmode::compose_down "${HOME}/Containers/forgejo" || status=1
    devmode::compose_down "${HOME}/Containers/mailpit" || status=1
    return "$status"
}
