# devmode environment configuration for Larakit
#
devmode_status() {
    local status=0
    devmode::docker_desktop_status || status=1
    devmode::brew_status dnsmasq || status=1
    devmode::docker_status "laradock-workspace-1" || status=1
    return "$status"
}

devmode_up() {
    local status=0
    devmode::docker_desktop_launch || status=1
    devmode::brew_start dnsmasq || status=1
    larakit up || status=1
    return "$status"
}

devmode_down() {
    local status=0
    larakit down || status=1
    devmode::brew_stop dnsmasq || status=1
    return "$status"
}
